# Generated by Django 4.0.3 on 2022-04-29 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
