# Generated by Django 4.0.3 on 2022-05-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_rename_data_added_comment_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
