# Generated by Django 4.0.3 on 2022-05-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='image',
        ),
    ]
