# Generated by Django 4.1.7 on 2023-03-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
