# Generated by Django 4.1.7 on 2023-03-18 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_email_delete_category_remove_post_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='To',
            new_name='to',
        ),
    ]
