# Generated by Django 4.1.7 on 2023-03-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_remove_email_id_email_messag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='messag_id',
            new_name='message_id',
        ),
    ]
