# Generated by Django 4.1.7 on 2023-03-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_rename_messag_id_email_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='message_id',
        ),
        migrations.AddField(
            model_name='email',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
