# Generated by Django 4.2 on 2023-05-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_academic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='category',
        ),
        migrations.AddField(
            model_name='email',
            name='Academic',
            field=models.CharField(default='unacademic', max_length=255),
        ),
    ]
