# Generated by Django 4.0.4 on 2023-05-08 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0026_remove_email_category_email_academic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='Academic',
        ),
        migrations.RemoveField(
            model_name='email',
            name='message_date',
        ),
        migrations.AddField(
            model_name='email',
            name='academic',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='email_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='email',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(default='no subject', max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(default='nobody'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to',
            field=models.CharField(max_length=255),
        ),
    ]
