# Generated by Django 4.0.4 on 2023-05-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_remove_email_academic_remove_email_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
